name: Latest Images
on:
  pull_request:
    branches:
      - latest
    paths-ignore:
      - ".github/workflows/*validate*.yml"
      - "**.md"
      - "system_files/shared/etc/bazaar/**"
  push:
    branches:
      - latest
    paths-ignore:
      - ".github/workflows/*validate*.yml"
      - "**.md"
      - "system_files/shared/etc/bazaar/**"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build-image-latest:
    name: Build Latest Images
    if: github.event_name != 'workflow_dispatch' || github.ref_name == 'latest'
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      stream_name: latest
      # FIXME: enable when ublue-os/akmods has ARM builds
      # architecture: '["aarch64","x86_64"]'
      architecture: '["x86_64"]'
